server:
  port: 8888
  servlet:
    context-path: /market
spring:
  datasource:
    url: jdbc:h2:mem:market;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  jooq:
    sql-dialect:

integrations:
  cart-service:
    url: http://localhost:8889/market-carts/
    read-timeout: 10000
    write-timeout: 7000
    connect-timeout: 7000

CartServiceIntegration-getCurrentCart: /api/v1/cart
CartServiceIntegration-delAllProductsFromBasket: /api/v1/cart/delete