version: '3'
networks:
  default:
    name: 'myNet'
    external: true
services:


  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
